### ISSUE TITLE
Remove package generates odd messages

### ISSUE THREAD

**Issue by athiffau** [sander3/laravel-gdpr#19]
when removing the package via composer you get the following messages:

```
soved/laravel-gdpr is not required in your composer.json and has not been removed
Dependency "laravel/framework" is also a root requirement, but is not explicitly whitelisted. Ignoring.
```

It's odd to get a message about removing laravel framework ?

**Comment by drbyte** [comment]
@athiffau It's not entirely unusual. It happens because this package's `composer.json` specifically mentions `laravel/framework` as a dependency and so does yours. Composer looked at the package you were removing and assessed whether it could/should remove all this package's stated dependencies. But it found that one of the ones listed by this package is also listed in your app's `composer.json`. So it reported that it's not going to remove everything this package lists.

It's harmless.

Many packages get around this by listing all the various `illuminate` dependencies individually. 
Unfortunately in this case it can't do that because it relies on some Foundation namespace things that are only defined by `laravel/framework`. (Looks like if it didn't use the FormRequest then it could just list `illuminate/queue` in `composer.json`)

**Comment by athiffau** [comment]
Thanks for the feedback. I personally had not seen this before.

**Comment by sander3** [comment]
@drbyte Thank you very much for describing the struggle I had with listing all the dependencies!
