### ISSUE TITLE
Is it possible to Login using Encrypted email.

### ISSUE THREAD

**Issue by xJoeyv** [sander3/laravel-gdpr#33]
Dear,

Is it possible to login using an encrypted email? Because the login doesn't run over the User model and gets the email attribute. Is there a way to achieve this?

**Comment by sander3** [comment]
Hi there,

It sure is. I'm thinking you'd want to combine the authentication with something like [sander3/laravel-magic-auth](https://github.com/sander3/laravel-magic-auth). You will be able to do this by extending the `Soved\Laravel\Gdpr\Http\Controllers\GdprController` and drafting your own `validateRequest()` method. Since the `GdprController` only does an API call to `Auth::check()` and `Auth::validate()` it is highly customisable. Don't forget to define a route to your new controller method!
